### ISSUE TITLE
thresholds display in scientific format

### ISSUE THREAD

**Issue by ben-wetherill** [massbays-tech/intro-to-r#2]
When I run View(thresholdMWR), the Fresh_1 thresholds display in scientific format and the Marine_1 thresholds display with 5 decimals.  Is it possible to make all of the thresholds display numerically?  Two decimal places would be fine for everything.

**Comment by fawda123** [comment]
Moving this to MassWateR repo https://github.com/massbays-tech/MassWateR/issues/32
